In [3]:
import pandas as pd
import os

In [5]:
Action_movies_df = pd.read_csv('Action_movies_df.csv')

In [7]:
Action_movies_df

     Unnamed: 0                         Title  Rating   Voting Duration
0             0               1. Gladiator II     6.5   (242K)   2h 28m
1             1            2. Fight or Flight     6.4    (12K)   1h 42m
2             2          3. Kraven the Hunter     5.5    (60K)    2h 7m
3             3                   4. Twisters     6.5   (173K)    2h 2m
4             4       5. Deadpool & Wolverine     7.5   (500K)    2h 8m
..          ...                           ...     ...      ...      ...
829         829  1249. Sehnsucht nach Firdaws     8.5      (6)   1h 43m
830         830         1259. Lealtad o Morir     8.2      (9)   1h 27m
831         831          1263. Duelo De Capos     6.2     (33)   1h 23m
832         832                 1279. Gadha17     8.0     (12)   1h 30m
833         833            1319. Luna de Hiel     5.8     (25)   1h 23m

[834 rows x 5 columns]

In [9]:
Action_movies_df["Genre"] = "Action"

In [11]:
Action_movies_df

,Unnamed: 0,Title,Rating,Voting,Duration,Genre
0,0,1. Gladiator II,6.5,(242K),2h 28m,Action
1,1,2. Fight or Flight,6.4,(12K),1h 42m,Action
2,2,3. Kraven the Hunter,5.5,(60K),2h 7m,Action
3,3,4. Twisters,6.5,(173K),2h 2m,Action
4,4,5. Deadpool & Wolverine,7.5,(500K),2h 8m,Action
...,...,...,...,...,...,...
829,829,1249. Sehnsucht nach Firdaws,8.5,(6),1h 43m,Action
830,830,1259. Lealtad o Morir,8.2,(9),1h 27m,Action
831,831,1263. Duelo De Capos,6.2,(33),1h 23m,Action
832,832,1279. Gadha17,8.0,(12),1h 30m,Action
833,833,1319. Luna de Hiel,5.8,(25),1h 23m,Action

In [33]:
Action_movies = Action_movies_df.drop(columns="Unnamed: 0")

In [35]:
Action_movies

                            Title  Rating   Voting Duration   Genre
0                 1. Gladiator II     6.5   (242K)   2h 28m  Action
1              2. Fight or Flight     6.4    (12K)   1h 42m  Action
2            3. Kraven the Hunter     5.5    (60K)    2h 7m  Action
3                     4. Twisters     6.5   (173K)    2h 2m  Action
4         5. Deadpool & Wolverine     7.5   (500K)    2h 8m  Action
..                            ...     ...      ...      ...     ...
829  1249. Sehnsucht nach Firdaws     8.5      (6)   1h 43m  Action
830         1259. Lealtad o Morir     8.2      (9)   1h 27m  Action
831          1263. Duelo De Capos     6.2     (33)   1h 23m  Action
832                 1279. Gadha17     8.0     (12)   1h 30m  Action
833            1319. Luna de Hiel     5.8     (25)   1h 23m  Action

[834 rows x 5 columns]

In [37]:
Action_movies.to_csv("Action_movies.csv")

In [19]:
Animation_movies_df = pd.read_csv('Animation_movies_df.csv')

In [21]:
Animation_movies_df

,Unnamed: 0,Title,Rating,Voting,Duration
0,0,1. Paddington in Peru,6.7,(24K),1h 46m
1,1,2. The Wild Robot,8.2,(171K),1h 42m
2,2,3. Mufasa: The Lion King,6.6,(68K),1h 58m
3,3,4. Moana 2,6.6,(106K),1h 40m
4,4,5. Flow,7.9,(80K),1h 25m
...,...,...,...,...,...
229,229,327. Young doctor's notes,3.5,(7),1h 26m
230,230,332. Skazochnyy patrul. Shou prodolzhayetsya,7.2,(11),1h 5m
231,231,345. 2475 Dawn of Revolution,6.3,(153),2h 7m
232,232,363. Woolina and the No Birds,8.1,(50),1h 20m
233,233,378. Ekip: Siberay - Günes Firtinasi,6.0,(14),1h 12m

In [23]:
Animation_movies_df["Genre"] = "Animation"

In [25]:
Animation_movies = Animation_movies_df.drop(columns="Unnamed: 0")

In [31]:
Animation_movies.to_csv("Animation_movies.csv")

In [29]:
Animation_movies

,Title,Rating,Voting,Duration,Genre
0,1. Paddington in Peru,6.7,(24K),1h 46m,Animation
1,2. The Wild Robot,8.2,(171K),1h 42m,Animation
2,3. Mufasa: The Lion King,6.6,(68K),1h 58m,Animation
3,4. Moana 2,6.6,(106K),1h 40m,Animation
4,5. Flow,7.9,(80K),1h 25m,Animation
...,...,...,...,...,...
229,327. Young doctor's notes,3.5,(7),1h 26m,Animation
230,332. Skazochnyy patrul. Shou prodolzhayetsya,7.2,(11),1h 5m,Animation
231,345. 2475 Dawn of Revolution,6.3,(153),2h 7m,Animation
232,363. Woolina and the No Birds,8.1,(50),1h 20m,Animation
233,378. Ekip: Siberay - Günes Firtinasi,6.0,(14),1h 12m,Animation

In [39]:
Biography_movies_df = pd.read_csv('Biography_movies_df.csv')

In [41]:
Biography_movies_df

,Unnamed: 0,Title,Rating,Voting,Duration
0,0,1. A Complete Unknown,7.4,(85K),2h 21m
1,1,2. Queen of the Ring,6.4,(1.7K),2h 20m
2,2,3. I'm Still Here,8.2,(109K),2h 17m
3,3,4. The Apprentice,7.1,(58K),2h 2m
4,4,5. Better Man,7.6,(29K),2h 15m
...,...,...,...,...,...
276,276,415. 87 Candles,9.0,(10),55m
277,277,417. Giannis Spanos: Piso ap' ti markiza,7.8,(17),1h 58m
278,278,"418. Lupicinio Rodrigues, Confissões de um Sof...",7.0,(6),1h 39m
279,279,419. Davaj Paradiso,9.1,(28),1h 3m
280,280,424. Gevart,7.3,(70),34m

In [43]:
Biography_movies_df["Genre"] = "Biography"

In [45]:
Biography_movies = Biography_movies_df.drop(columns="Unnamed: 0")

In [47]:
Biography_movies.to_csv("Biography_movies.csv")

In [49]:
Family_movies_df = pd.read_csv('Family_movies_df.csv')

In [51]:
Family_movies_df

     Unnamed: 0                               Title  Rating   Voting Duration
0             0               1. Paddington in Peru     6.7    (24K)   1h 46m
1             1            2. Mufasa: The Lion King     6.6    (68K)   1h 58m
2             2                          3. Moana 2     6.6   (106K)   1h 40m
3             3                             4. Flow     7.9    (80K)   1h 25m
4             4             5. Sonic the Hedgehog 3     6.9    (62K)   1h 50m
..          ...                                 ...     ...      ...      ...
355         355                     490. Selebryata     3.8     (20)   1h 33m
356         356                505. Childhood Tales     7.3     (22)    1h 3m
357         357  509. Beyaz Zenciler: Yapim Asamasi     8.6      (5)      55m
358         358                    527. Tui Ke Amar     6.6      (6)   1h 54m
359         359      530. Gyakorlat teszi a mestert     6.1     (15)      46m

[360 rows x 5 columns]

In [53]:
Family_movies_df["Genre"] = "Family"

In [55]:
Family_movies = Family_movies_df.drop(columns="Unnamed: 0")

In [57]:
Family_movies.to_csv("Family_movies.csv")

In [59]:
Family_movies

                                  Title  Rating   Voting Duration   Genre
0                 1. Paddington in Peru     6.7    (24K)   1h 46m  Family
1              2. Mufasa: The Lion King     6.6    (68K)   1h 58m  Family
2                            3. Moana 2     6.6   (106K)   1h 40m  Family
3                               4. Flow     7.9    (80K)   1h 25m  Family
4               5. Sonic the Hedgehog 3     6.9    (62K)   1h 50m  Family
..                                  ...     ...      ...      ...     ...
355                     490. Selebryata     3.8     (20)   1h 33m  Family
356                505. Childhood Tales     7.3     (22)    1h 3m  Family
357  509. Beyaz Zenciler: Yapim Asamasi     8.6      (5)      55m  Family
358                    527. Tui Ke Amar     6.6      (6)   1h 54m  Family
359      530. Gyakorlat teszi a mestert     6.1     (15)      46m  Family

[360 rows x 5 columns]

In [61]:
Fantasy_movies_df = pd.read_csv('Fantasy_movies_df.csv')

In [63]:
Fantasy_movies_df

,Unnamed: 0,Title,Rating,Voting,Duration
0,0,1. Nosferatu,7.2,(203K),2h 12m
1,1,2. Beetlejuice Beetlejuice,6.6,(151K),1h 45m
2,2,3. Wicked,7.5,(163K),2h 40m
3,3,4. The Life of Chuck,7.5,(707),1h 50m
4,4,5. Moana 2,6.6,(106K),1h 40m
...,...,...,...,...,...
323,323,417. Darker Than Night,4.7,(24),1h 22m
324,324,438. Young doctor's notes,3.5,(7),1h 26m
325,325,445. Skazochnyy patrul. Shou prodolzhayetsya,7.2,(11),1h 5m
326,326,"447. Bryson, the Demon Slayer",4.4,(12),59m
327,327,451. Kan dao ling hun de na zhi yan shi gong,3.2,(12),2h 4m

In [65]:
Fantasy_movies_df["Genre"] = "Fantasy"

In [67]:
Fantasy_movies = Fantasy_movies_df.drop(columns="Unnamed: 0")

In [69]:
Fantasy_movies.to_csv("Fantasy_movies.csv")

In [71]:
Fantasy_movies

,Title,Rating,Voting,Duration,Genre
0,1. Nosferatu,7.2,(203K),2h 12m,Fantasy
1,2. Beetlejuice Beetlejuice,6.6,(151K),1h 45m,Fantasy
2,3. Wicked,7.5,(163K),2h 40m,Fantasy
3,4. The Life of Chuck,7.5,(707),1h 50m,Fantasy
4,5. Moana 2,6.6,(106K),1h 40m,Fantasy
...,...,...,...,...,...
323,417. Darker Than Night,4.7,(24),1h 22m,Fantasy
324,438. Young doctor's notes,3.5,(7),1h 26m,Fantasy
325,445. Skazochnyy patrul. Shou prodolzhayetsya,7.2,(11),1h 5m,Fantasy
326,"447. Bryson, the Demon Slayer",4.4,(12),59m,Fantasy
327,451. Kan dao ling hun de na zhi yan shi gong,3.2,(12),2h 4m,Fantasy

In [5]:
folder_path = 'testcsv'

csv_files = [file for file in os.listdir(folder_path) if file.endswith('.csv')]

df_list = [pd.read_csv(os.path.join(folder_path, file)) for file in csv_files]
merged_movie_list = pd.concat(df_list, ignore_index=True)

merged_movie_list.to_csv('merged_movie_file.csv', index=False)

In [7]:
import pandas as pd
import re

df = pd.read_csv('merged_movie_file.csv')

df['Title'] = df['Title'].str.replace(r'^\d+\.\s*', '', regex=True)

df.to_csv('merged&cleaned_movies.csv', index=False)

In [11]:
import pandas as pd

df = pd.read_csv('merged&cleaned_movies.csv')

df['Voting'] = df['Voting'].astype(str)

df['Voting'] = df['Voting'].str.replace(r'[\(\)]', '', regex=True)

df['Voting'] = df['Voting'].str.replace(r'^-', '', regex=True)

df.to_csv('merged&cleaned_movies1.csv', index=False)

In [13]:
import pandas as pd


df = pd.read_csv('merged&cleaned_movies1.csv')

def convert_k_to_int(value):
    value = str(value).strip().upper()
    if 'K' in value:
        try:
            return int(float(value.replace('K', '')) * 1000)
        except ValueError:
            return None
    else:
        try:
            return int(value)
        except ValueError:
            return None

df['Voting'] = df['Voting'].apply(convert_k_to_int)

df.to_csv('Cleaned_movies_list.csv', index=False)

In [1]:
import mysql.connector as db
import pandas as pd

In [3]:
db_con = db.connect(
       host = "localhost",
       user = "Harshu",
       password = "root",
       database = "world"

)

In [5]:
curr = db_con.cursor()

In [7]:
df = pd.read_csv("Cleaned_movies_list.csv")

In [9]:
df

,Unnamed: 0,Title,Rating,Voting,Duration,Genre
0,0,Gladiator II,6.5,242000,2h 28m,Action
1,1,Fight or Flight,6.4,12000,1h 42m,Action
2,2,Kraven the Hunter,5.5,60000,2h 7m,Action
3,3,Twisters,6.5,173000,2h 2m,Action
4,4,Deadpool & Wolverine,7.5,500000,2h 8m,Action
...,...,...,...,...,...,...
2032,323,Darker Than Night,4.7,24,1h 22m,Fantasy
2033,324,Young doctor's notes,3.5,7,1h 26m,Fantasy
2034,325,Skazochnyy patrul. Shou prodolzhayetsya,7.2,11,1h 5m,Fantasy
2035,326,"Bryson, the Demon Slayer",4.4,12,59m,Fantasy
2036,327,Kan dao ling hun de na zhi yan shi gong,3.2,12,2h 4m,Fantasy

In [11]:
df = df.drop(columns="Unnamed: 0")

In [13]:
df

,Title,Rating,Voting,Duration,Genre
0,Gladiator II,6.5,242000,2h 28m,Action
1,Fight or Flight,6.4,12000,1h 42m,Action
2,Kraven the Hunter,5.5,60000,2h 7m,Action
3,Twisters,6.5,173000,2h 2m,Action
4,Deadpool & Wolverine,7.5,500000,2h 8m,Action
...,...,...,...,...,...
2032,Darker Than Night,4.7,24,1h 22m,Fantasy
2033,Young doctor's notes,3.5,7,1h 26m,Fantasy
2034,Skazochnyy patrul. Shou prodolzhayetsya,7.2,11,1h 5m,Fantasy
2035,"Bryson, the Demon Slayer",4.4,12,59m,Fantasy
2036,Kan dao ling hun de na zhi yan shi gong,3.2,12,2h 4m,Fantasy

In [17]:
df.values

array([['Gladiator II', 6.5, 242000, '2h 28m', 'Action'],
       ['Fight or Flight', 6.4, 12000, '1h 42m', 'Action'],
       ['Kraven the Hunter', 5.5, 60000, '2h 7m', 'Action'],
       ...,
       ['Skazochnyy patrul. Shou prodolzhayetsya', 7.2, 11, '1h 5m',
        'Fantasy'],
       ['Bryson, the Demon Slayer', 4.4, 12, '59m', 'Fantasy'],
       ['Kan dao ling hun de na zhi yan shi gong', 3.2, 12, '2h 4m',
        'Fantasy']], dtype=object)

In [19]:
list(map(tuple, df.values))

[('Gladiator II', 6.5, 242000, '2h 28m', 'Action'),
 ('Fight or Flight', 6.4, 12000, '1h 42m', 'Action'),
 ('Kraven the Hunter', 5.5, 60000, '2h 7m', 'Action'),
 ('Twisters', 6.5, 173000, '2h 2m', 'Action'),
 ('Deadpool & Wolverine', 7.5, 500000, '2h 8m', 'Action'),
 ('Dune: Part Two', 8.5, 633000, '2h 46m', 'Action'),
 ('The Ministry of Ungentlemanly Warfare', 6.8, 137000, '2h 2m', 'Action'),
 ('Freaky Tales', 6.3, 5900, '1h 47m', 'Action'),
 ('Venom: The Last Dance', 6.0, 123000, '1h 50m', 'Action'),
 ('The Beekeeper', 6.3, 159000, '1h 45m', 'Action'),
 ('Sonic the Hedgehog 3', 6.9, 62000, '1h 50m', 'Action'),
 ('Civil War', 7.0, 240000, '1h 49m', 'Action'),
 ('Furiosa: A Mad Max Saga', 7.5, 288000, '2h 28m', 'Action'),
 ('The Count of Monte-Cristo', 7.6, 36000, '2h 58m', 'Action'),
 ('The Fall Guy', 6.8, 224000, '2h 6m', 'Action'),
 ('Carry-On', 6.5, 169000, '1h 59m', 'Action'),
 ('Road House', 6.2, 169000, '2h 1m', 'Action'),
 ('Madame Web', 4.0, 102000, '1h 56m', 'Action'),
 ('Transformers One', 7.6, 52000, '1h 44m', 'Action'),
 ('Borderlands', 4.7, 49000, '1h 41m', 'Action'),
 ('Homestead', 5.3, 3900, '1h 52m', 'Action'),
 ('Elevation', 5.6, 23000, '1h 31m', 'Action'),
 ('Rebel Ridge', 6.8, 90000, '2h 11m', 'Action'),
 ('The Crow', 4.7, 36000, '1h 51m', 'Action'),
 ('Godzilla x Kong: The New Empire', 6.0, 123000, '1h 55m', 'Action'),
 ('Love Lies Bleeding', 6.6, 58000, '1h 44m', 'Action'),
 ('Azrael', 5.4, 12000, '1h 26m', 'Action'),
 ('Arcadian', 5.5, 24000, '1h 32m', 'Action'),
 ('Pushpa: The Rule - Part 2', 6.1, 57000, '3h 21m', 'Action'),
 ('Argylle', 5.6, 93000, '2h 19m', 'Action'),
 ('Bad Boys: Ride or Die', 6.5, 101000, '1h 55m', 'Action'),
 ('Kingdom of the Planet of the Apes', 6.9, 153000, '2h 25m', 'Action'),
 ('The Lord of the Rings: The War of the Rohirrim',
  6.3,
  32000,
  '2h 14m',
  'Action'),
 ('Drive-Away Dolls', 5.4, 24000, '1h 24m', 'Action'),
 ('Kung Fu Panda 4', 6.3, 69000, '1h 34m', 'Action'),
 ('Red One', 6.3, 141000, '2h 3m', 'Action'),
 ('Fighter', 6.2, 52000, '2h 46m', 'Action'),
 ("The Killer's Game", 5.8, 18000, '1h 44m', 'Action'),
 ('Damsel', 6.1, 110000, '1h 50m', 'Action'),
 ('The Instigators', 6.2, 38000, '1h 41m', 'Action'),
 ('Monkey Man', 6.8, 93000, '2h 1m', 'Action'),
 ('Dirty Angels', 4.4, 3600, '1h 44m', 'Action'),
 ('Maharaja', 8.4, 69000, '2h 21m', 'Action'),
 ('Thelma', 7.0, 23000, '1h 38m', 'Action'),
 ('The Union', 5.4, 54000, '1h 47m', 'Action'),
 ('The Silent Hour', 6.1, 8000, '1h 39m', 'Action'),
 ('Land of Bad', 6.6, 52000, '1h 53m', 'Action'),
 ('Werewolves', 4.4, 7300, '1h 33m', 'Action'),
 ('Hellboy: The Crooked Man', 4.5, 14000, '1h 39m', 'Action'),
 ('Blitz', 6.2, 17000, '2h', 'Action'),
 ('Solo Leveling: ReAwakening', 8.8, 13000, '2h 1m', 'Action'),
 ('Attack on Titan the Movie: The Last Attack',
  9.2,
  17000,
  '2h 25m',
  'Action'),
 ('William Tell', 5.7, 2800, '2h 13m', 'Action'),
 ('Uglies', 4.7, 33000, '1h 40m', 'Action'),
 ('Beverly Hills Cop: Axel F', 6.4, 82000, '1h 58m', 'Action'),
 ('The Killer', 5.7, 13000, '2h 6m', 'Action'),
 ('The Fix', 4.7, 1400, '1h 38m', 'Action'),
 ('Apocalypse Z: The Beginning of the End', 6.1, 20000, '1h 57m', 'Action'),
 ('Lift', 5.5, 50000, '1h 47m', 'Action'),
 ('Kalki 2898 AD', 7.0, 67000, '3h', 'Action'),
 ('Survive', 4.5, 2800, '1h 30m', 'Action'),
 ('Absolution', 5.2, 8500, '1h 52m', 'Action'),
 ('Weekend in Taipei', 5.7, 5100, '1h 40m', 'Action'),
 ('Rebel Moon - Part Two: The Scargiver', 5.3, 60000, '2h 2m', 'Action'),
 ('Atlas', 5.6, 56000, '1h 58m', 'Action'),
 ('Old Guy', 5.2, 2700, '1h 34m', 'Action'),
 ('Jackpot!', 5.8, 31000, '1h 46m', 'Action'),
 ('They Call Her Death', 5.4, 164, '1h 32m', 'Action'),
 ('Under Paris', 5.2, 37000, '1h 44m', 'Action'),
 ('Descendants: The Rise of Red', 4.7, 7200, '1h 31m', 'Action'),
 ('The Shadow Strays', 6.5, 9400, '2h 24m', 'Action'),
 ('40 Acres', 7.0, 195, '1h 53m', 'Action'),
 ('Twilight of the Warriors: Walled In', 7.0, 10000, '2h 6m', 'Action'),
 ('Watchmen: Chapter I', 7.1, 6800, '1h 23m', 'Action'),
 ('Armor', 3.6, 4300, '1h 29m', 'Action'),
 ('Brothers', 5.4, 13000, '1h 29m', 'Action'),
 ('Canary Black', 5.4, 12000, '1h 41m', 'Action'),
 ('No Way Up', 4.6, 11000, '1h 30m', 'Action'),
 ('Classified', 3.7, 2700, '1h 45m', 'Action'),
 ('The Prosecutor', 6.6, 2300, '1h 57m', 'Action'),
 ('Aftermath', 5.1, 4200, '1h 37m', 'Action'),
 ('Trigger Warning', 4.6, 20000, '1h 46m', 'Action'),
 ('Take Cover', 5.1, 2600, '1h 30m', 'Action'),
 ('Baby John', 5.2, 17000, '2h 39m', 'Action'),
 ('Marco', 6.8, 22000, '2h 25m', 'Action'),
 ('Amaran', 8.1, 19000, '2h 47m', 'Action'),
 ('Striking Rescue', 5.6, 612, '1h 51m', 'Action'),
 ('11 Rebels', 6.2, 548, '2h 35m', 'Action'),
 ('Uprising', 6.6, 5700, '2h 6m', 'Action'),
 ('Harbin', 6.2, 854, '1h 48m', 'Action'),
 ('Chief of Station', 4.7, 4700, '1h 37m', 'Action'),
 ('Long Gone Heroes', 5.1, 1200, '1h 41m', 'Action'),
 ('Watchmen: Chapter II', 7.0, 3300, '1h 30m', 'Action'),
 ('Megamind vs. The Doom Syndicate', 2.5, 5600, '1h 23m', 'Action'),
 ('Relay', 7.5, 112, '1h 52m', 'Action'),
 ('Cash Out', 4.8, 3000, '1h 32m', 'Action'),
 ('Saripodhaa Sanivaaram', 7.0, 9500, '2h 46m', 'Action'),
 ('Sikandar Ka Muqaddar', 6.0, 24000, '2h 22m', 'Action'),
 ('Damaged', 4.7, 7400, '1h 37m', 'Action'),
 ('Article 370', 7.8, 25000, '2h 38m', 'Action'),
 ("My Hero Academia: You're Next", 7.0, 2500, '1h 50m', 'Action'),
 ('Gunner', 3.2, 2800, '1h 46m', 'Action'),
 ('Boneyard', 4.1, 5100, '1h 36m', 'Action'),
 ('Duchess', 4.6, 1500, '1h 54m', 'Action'),
 ('Red Right Hand', 5.5, 6000, '1h 51m', 'Action'),
 ('Hounds of War', 4.5, 1900, '1h 35m', 'Action'),
 ('Night Call', 6.8, 2200, '1h 37m', 'Action'),
 ('Aavesham', 7.8, 28000, '2h 35m', 'Action'),
 ('Justice League: Crisis on Infinite Earths - Part One',
  6.2,
  8600,
  '1h 33m',
  'Action'),
 ('Role Play', 5.5, 19000, '1h 40m', 'Action'),
 ('Demon Slayer: Kimetsu No Yaiba - To the Hashira Training',
  7.2,
  8700,
  '1h 44m',
  'Action'),
 ('I, the Executioner', 6.3, 1900, '1h 58m', 'Action'),
 ('My Spy: The Eternal City', 5.7, 11000, '1h 52m', 'Action'),
 ('Drive Back', 4.5, 565, '1h 34m', 'Action'),
 ('Badland Hunters', 5.9, 12000, '1h 47m', 'Action'),
 ('Dan Da Dan: First Encounter', 8.2, 2800, '1h 23m', 'Action'),
 ('Justice League: Crisis on Infinite Earths - Part Three',
  6.1,
  4700,
  '1h 34m',
  'Action'),
 ('Chandu Champion', 7.8, 34000, '2h 22m', 'Action'),
 ('72 Hours', 4.1, 318, '1h 27m', 'Action'),
 ('Singham Again', 4.7, 75000, '2h 24m', 'Action'),
 ('Terminator: Skynet Rising', 6.6, 272, '1h 28m', 'Action'),
 ('Officer Black Belt', 6.9, 8500, '1h 48m', 'Action'),
 ('Hitpig', 5.1, 1000, '1h 26m', 'Action'),
 ('Ultraman: Rising', 6.9, 6500, '1h 57m', 'Action'),
 ('Jigra', 6.0, 24000, '2h 33m', 'Action'),
 ('Cloud', 6.3, 1300, '2h 4m', 'Action'),
 ('Mafia Wars', 3.6, 262, '1h 34m', 'Action'),
 ('Toofan', 7.4, 8400, '2h 25m', 'Action'),
 ('Seeds', 5.0, 196, '1h 22m', 'Action'),
 ('Panda Plan', 5.1, 1400, '1h 39m', 'Action'),
 ('Code 8: Part II', 5.7, 16000, '1h 40m', 'Action'),
 ('Kanguva', 4.5, 15000, '2h 32m', 'Action'),
 ('Devara Part 1', 6.0, 21000, '2h 56m', 'Action'),
 ('The Courier', 6.0, 4500, '1h 41m', 'Action'),
 ("Don't Mess with Grandma", 5.6, 263, '1h 21m', 'Action'),
 ('The Greatest of All Time', 5.7, 23000, '3h 3m', 'Action'),
 ('Vettaiyan', 7.0, 40000, '2h 43m', 'Action'),
 ('London Calling', 7.6, 27, '1h 49m', 'Action'),
 ('Joe Baby', 5.9, 56, '1h 26m', 'Action'),
 ('River of Blood', 5.1, 1900, '1h 26m', 'Action'),
 ('Pani', 6.9, 3200, '2h 23m', 'Action'),
 ('Bohurupi', 8.0, 1600, '2h 35m', 'Action'),
 ('Overlord: The Sacred Kingdom', 6.9, 1300, '2h 15m', 'Action'),
 ('Escape', 6.4, 2100, '1h 34m', 'Action'),
 ('Rifle Club', 7.0, 4500, '1h 53m', 'Action'),
 ('One Fast Move', 5.0, 2200, '1h 48m', 'Action'),
 ('Hagen', 6.0, 1300, '2h 19m', 'Action'),
 ('Darkness of Man', 4.7, 3200, '1h 49m', 'Action'),
 ('Baby Invasion', 4.7, 530, '1h 20m', 'Action'),
 ("Son's Will", 7.4, 939, '2h 28m', 'Action'),
 ('The Thundermans Return', 5.0, 1900, '1h 10m', 'Action'),
 ('Operation Valentine', 5.3, 1400, '2h 13m', 'Action'),
 ('Yodha', 5.7, 8900, '2h 10m', 'Action'),
 ('A Legend', 4.7, 968, '2h 9m', 'Action'),
 ('Karma', 7.8, 1400, '2h 47m', 'Action'),
 ('Air Force One Down', 4.4, 2900, '1h 24m', 'Action'),
 ('All the Lost Ones', 3.7, 263, '1h 46m', 'Action'),
 ('Kill Em All 2', 4.1, 1400, '1h 28m', 'Action'),
 ('Paradox Effect', 5.9, 8700, '1h 27m', 'Action'),
 ('Handsome Guys', 6.5, 914, '1h 41m', 'Action'),
 ('Bougainvillea', 6.4, 3300, '2h 18m', 'Action'),
 ('The Family Star', 5.4, 5600, '2h 39m', 'Action'),
 ('Justice League: Crisis on Infinite Earths - Part Two',
  5.5,
  5500,
  '1h 34m',
  'Action'),
 ('Latency', 4.2, 2800, '1h 34m', 'Action'),
 ('The Roundup: Punishment', 6.6, 5500, '1h 49m', 'Action'),
 ('Cells at Work!', 6.7, 314, '1h 49m', 'Action'),
 ('Gladiators', 4.5, 102, '1h 35m', 'Action'),
 ('Gatao: Like Father Like Son', 5.7, 224, '2h 11m', 'Action'),
 ("The Tiger's Apprentice", 5.7, 2200, '1h 24m', 'Action'),
 ('Levels', 5.0, 1600, '1h 33m', 'Action'),
 ('Die Hart 2: Die Harter', 4.3, 5600, '1h 32m', 'Action'),
 ('Khadaan', 7.1, 2200, '2h 17m', 'Action'),
 ('The Wages of Fear', 4.6, 4200, '1h 44m', 'Action'),
 ('Dark Match', 5.4, 991, '1h 34m', 'Action'),
 ('Agent Recon', 2.4, 705, '1h 25m', 'Action'),
 ('Arena Wars', 4.9, 2200, '1h 36m', 'Action'),
 ('Vedaa', 6.0, 4400, '2h 25m', 'Action'),
 ('The Quiet Ones', 6.3, 765, '1h 50m', 'Action'),
 ('Bureau 749', 4.0, 563, '2h 3m', 'Action'),
 ('Alien: Rubicon', 2.4, 355, '1h 26m', 'Action'),
 ('Prey', 3.7, 3300, '1h 26m', 'Action'),
 ('Garudan', 7.1, 3400, '2h 13m', 'Action'),
 ('Viduthalai Part 2', 7.8, 16000, '2h 50m', 'Action'),
 ('The Price of Money: A Largo Winch Adventure',
  5.1,
  1200,
  '1h 40m',
  'Action'),
 ('Everybody Loves Jenifa', 8.2, 91, '2h 15m', 'Action'),
 ('Black Heat', 8.4, 128, '1h 33m', 'Action'),
 ('Hanu Man', 7.7, 29000, '2h 38m', 'Action'),
 ('Life After Fighting', 6.4, 2100, '2h 6m', 'Action'),
 ('Alienoid: The Return to the Future', 6.5, 2700, '2h 2m', 'Action'),
 ('Continental Split', 3.5, 561, '1h 28m', 'Action'),
 ('City Hunter', 6.3, 5700, '1h 42m', 'Action'),
 ('The Clean Up Crew', 4.1, 1200, '1h 35m', 'Action'),
 ('Bagheera', 6.7, 7400, '2h 38m', 'Action'),
 ('A.R.M', 7.1, 8800, '2h 30m', 'Action'),
 ('One More Shot', 5.4, 3700, '1h 43m', 'Action'),
 ('Sasan', 8.7, 78, '2h 35m', 'Action'),
 ('Anaconda', 4.9, 651, '1h 24m', 'Action'),
 ('Dominique', 5.3, 2300, '1h 40m', 'Action'),
 ('Trouble', 6.2, 7000, '1h 38m', 'Action'),
 ('Sunray: Fallen Soldier', 4.3, 684, '1h 55m', 'Action'),
 ('Auron Mein Kahan Dum Tha', 6.5, 41000, '2h 30m', 'Action'),
 ('Vanvaas', 6.6, 1400, '2h 40m', 'Action'),
 ('Invasion', 4.8, 720, '1h 31m', 'Action'),
 ('Golden Kamuy', 6.3, 2600, '2h 7m', 'Action'),
 ('Hijack 1971', 6.8, 3400, '1h 40m', 'Action'),
 ('Savi', 6.1, 35000, '2h 6m', 'Action'),
 ('Six jours', 5.7, 235, '1h 35m', 'Action'),
 ('Tillu Square', 6.6, 3400, '2h 17m', 'Action'),
 ('Guntur Kaaram', 5.4, 25000, '2h 39m', 'Action'),
 ('Raayan', 6.5, 11000, '2h 25m', 'Action'),
 ('Operation Blood Hunt', 3.4, 502, '1h 33m', 'Action'),
 ('Thangalaan', 6.6, 6700, '2h 36m', 'Action'),
 ('Kingdom 4: Return of the Great General', 7.1, 1400, '2h 25m', 'Action'),
 ('Crakk: Jeetega... Toh Jiyegaa', 4.7, 6500, '2h 34m', 'Action'),
 ('Agni', 7.2, 15000, '2h 2m', 'Action'),
 ('Baki Hanma VS Kengan Ashura', 5.7, 2000, '1h 2m', 'Action'),
 ('Je Jatt Vigarh Gya', 5.6, 830, '2h 12m', 'Action'),
 ('Lights Out', 4.9, 1800, '1h 30m', 'Action'),
 ('Murder Company', 3.6, 1600, '1h 26m', 'Action'),
 ('Angels Fallen: Warriors of Peace', 4.8, 5800, '1h 43m', 'Action'),
 ('Bade Miyan Chote Miyan', 3.7, 39000, '2h 43m', 'Action'),
 ('Operation: Raqqa', 5.5, 272, '1h 47m', 'Action'),
 ('Wynonna Earp: Vengeance', 5.5, 1600, '1h 36m', 'Action'),
 ('Revolver', 5.4, 904, '1h 54m', 'Action'),
 ('GTMax', 5.0, 1300, '1h 40m', 'Action'),
 ('Ka Whawhai Tonu', 7.2, 187, '1h 55m', 'Action'),
 ('Eagle', 5.9, 4900, '2h 39m', 'Action'),
 ("Devil's Knight", 5.3, 940, '1h 30m', 'Action'),
 ('Max', 7.1, 3400, '2h 12m', 'Action'),
 ('Freedom', 5.9, 1400, '1h 50m', 'Action'),
 ('Cesium Fallout', 6.4, 825, '2h 15m', 'Action'),
 ('Wanted Man', 4.8, 2600, '1h 25m', 'Action'),
 ('Outlaw', 5.2, 952, '1h 22m', 'Action'),
 ('No Time to Spy: A Loud House Movie', 6.4, 478, '1h 21m', 'Action'),
 ('Love, Courage and the Battle of Bushy Run', 5.0, 188, '1h 53m', 'Action'),
 ('KA', 7.0, 1700, '2h 31m', 'Action'),
 ('Jorge da Capadócia', 6.0, 153, '1h 59m', 'Action'),
 ('Mura', 7.3, 6300, '2h 9m', 'Action'),
 ('The Last Kumite', 4.6, 2300, '1h 45m', 'Action'),
 ('Sixty Minutes', 5.7, 5200, '1h 28m', 'Action'),
 ('Yudhra', 5.0, 13000, '2h 22m', 'Action'),
 ('Utopia', 3.6, 381, '1h 31m', 'Action'),
 ('The Twisters', 2.5, 357, '1h 26m', 'Action'),
 ('The Last Front', 5.5, 623, '1h 38m', 'Action'),
 ('The Last of Us: Immunity', 4.4, 28, '1h 4m', 'Action'),
 ('Baby Assassins: Nice Days', 7.3, 327, '1h 43m', 'Action'),
 ('Death Whisperer 2', 6.3, 1500, '1h 50m', 'Action'),
 ('Kahar: Kapla High Council', 7.0, 478, '1h 42m', 'Action'),
 ('UI', 6.8, 5700, '2h 15m', 'Action'),
 ('Citizen of a Kind', 6.7, 867, '1h 54m', 'Action'),
 ('The Hangman', 3.3, 1000, '1h 32m', 'Action'),
 ('The Lockdown', 4.3, 622, '1h 57m', 'Action'),
 ('200% Wolf', 5.9, 1300, '1h 38m', 'Action'),
 ('Elyas', 6.1, 1500, '1h 45m', 'Action'),
 ('Stuntman', 6.9, 191, '1h 54m', 'Action'),
 ('Bidurbhai', 9.2, 393, '2h 28m', 'Action'),
 ('Shark Warning', 3.3, 308, '1h 34m', 'Action'),
 ('War of the Worlds: Extinction', 3.0, 210, '1h 24m', 'Action'),
 ('Nice Girls', 4.2, 1200, '1h 32m', 'Action'),
 ('How to Rob a Bank', 6.6, 4200, '1h 28m', 'Action'),
 ('Snow White and the Seven Samurai', 3.1, 309, '1h 28m', 'Action'),
 ('Alien Country', 4.4, 371, '1h 36m', 'Action'),
 ('Bangkok Dog', 4.8, 230, '1h 25m', 'Action'),
 ("Ryan's World the Movie: Titan Universe Adventure",
  1.8,
  704,
  '1h 20m',
  'Action'),
 ('Fight Another Day', 4.9, 372, '1h 37m', 'Action'),
 ('Cassino in Ischia', 4.3, 257, '1h 53m', 'Action'),
 ('24 Hours to D-Day', 3.7, 50, '1h 23m', 'Action'),
 ('WWII: Operation Phoenix', 5.7, 95, '1h 46m', 'Action'),
 ('Ayalaan', 5.9, 4000, '2h 35m', 'Action'),
 ('Alpha.', 6.9, 254, '1h 40m', 'Action'),
 ('Heart of the Hunter', 4.7, 2200, '1h 45m', 'Action'),
 ('12 to Midnight', 3.6, 289, '1h 36m', 'Action'),
 ('Troubleshooters', 6.5, 426, '1h 50m', 'Action'),
 ('Ghosts of Red Ridge', 3.3, 165, '1h 21m', 'Action'),
 ('Snatched', 5.6, 412, '1h 41m', 'Action'),
 ('Hellhound', 4.3, 513, '1h 43m', 'Action'),
 ('Operation Undead', 4.7, 427, '1h 50m', 'Action'),
 ('Mongol', 8.6, 98, '2h 35m', 'Action'),
 ('Black Creek', 9.6, 20, '1h 56m', 'Action'),
 ('Yolo', 6.9, 3800, '2h 9m', 'Action'),
 ('Ferry 2', 5.6, 3900, '1h 34m', 'Action'),
 ('Rogue Elements: A Ryan Drake Story', 4.5, 1000, '44m', 'Action'),
 ('Bionic', 4.3, 1700, '1h 50m', 'Action'),
 ('Roadkill', 3.7, 689, '1h 30m', 'Action'),
 ('Sheriff', 6.9, 1100, '2h 13m', 'Action'),
 ('Mission: Cross', 6.1, 2600, '1h 45m', 'Action'),
 ('Get Fast', 3.7, 463, '1h 28m', 'Action'),
 ('Rats!', 6.5, 148, '1h 25m', 'Action'),
 ('Bull Shark 2', 2.7, 198, '1h 15m', 'Action'),
 ('Kill Craft', 2.5, 372, '1h 39m', 'Action'),
 ('American Warrior', 8.8, 23, '1h 29m', 'Action'),
 ('Mr. Bachchan', 3.6, 5300, '2h 30m', 'Action'),
 ('Sucha Soorma', 6.3, 938, '2h 16m', 'Action'),
 ('Pusaka', 5.2, 179, '1h 30m', 'Action'),
 ('Agents', 3.3, 943, '1h 22m', 'Action'),
 ('S.T.A.L.K.E.R.: Shadow of the Zone', 5.2, 489, '1h 12m', 'Action'),
 ('Zero', 6.0, 80, '1h 28m', 'Action'),
 ('Ape X Mecha Ape: New World Order', 2.8, 144, '1h 27m', 'Action'),
 ('School of Magical Animals 3', 5.8, 334, '1h 45m', 'Action'),
 ('The Ballad of Davy Crockett', 4.6, 249, '1h 36m', 'Action'),
 ('Road Wars: Max Fury', 2.0, 365, '1h 23m', 'Action'),
 ('Sentimentaaal', 4.9, 990, '2h 15m', 'Action'),
 ('Virunnu', 4.1, 946, '2h 5m', 'Action'),
 ('Genis Aile 4: Cevahir & Ulvi', 4.9, 220, '1h 30m', 'Action'),
 ('Dange', 5.3, 803, '2h 34m', 'Action'),
 ('Dirty Money', 5.6, 158, '1h 40m', 'Action'),
 ('Martin', 2.2, 36000, '2h 27m', 'Action'),
 ('Clone Cops', 5.8, 246, '1h 36m', 'Action'),
 ('Hunting with Tigers', 5.6, 544, '1h 49m', 'Action'),
 ('Bachhala Malli', 8.2, 3900, '2h 20m', 'Action'),
 ('Pimpinero: Blood and Oil', 5.6, 565, '2h 1m', 'Action'),
 ('Malaikottai Vaaliban', 6.0, 4200, '2h 36m', 'Action'),
 ('The Friendly', 8.2, 17, '1h 41m', 'Action'),
 ('Hunt the Wicked', 5.4, 127, '1h 42m', 'Action'),
 ('Uninvited', 5.5, 110, '1h 33m', 'Action'),
 ('High Forces', 5.8, 547, '1h 59m', 'Action'),
 ('Big City Greens the Movie: Spacecation', 6.2, 559, '1h 23m', 'Action'),
 ('The Last Ronin', 4.9, 585, '1h 55m', 'Action'),
 ('Crisis Negotiators', 6.7, 729, '2h', 'Action'),
 ('Hide and Seek', 8.0, 55, '2h 10m', 'Action'),
 ('Chaari 111', 4.8, 264, '2h 10m', 'Action'),
 ('Razakar: The Silent Genocide of Hyderabad', 7.4, 5300, '2h 46m', 'Action'),
 ('Turbo', 5.9, 3600, '2h 35m', 'Action'),
 ('Escape from the 21st Century', 6.5, 931, '1h 38m', 'Action'),
 ('Captain Miller', 6.5, 8600, '2h 37m', 'Action'),
 ("Deaner '89", 5.9, 428, '1h 30m', 'Action'),
 ('Dharmarakshak Mahaveer Chhatrapati Sambhaji Maharaj',
  8.1,
  668,
  '2h 54m',
  'Action'),
 ('Nothing Even Matters', 5.7, 81, '1h 30m', 'Action'),
 ("First Nights at Freddy's", 9.3, 17, '1h 38m', 'Action'),
 ('Love You as the World Ends Final', 6.4, 39, '1h 55m', 'Action'),
 ('Bhaje Vaayu Vegam', 6.1, 764, '2h 16m', 'Action'),
 ('Purushothamudu', 5.1, 2300, '2h', 'Action'),
 ('The Grey Men', 6.5, 73, '1h 37m', 'Action'),
 ('Sorgavaasal', 6.6, 1400, '2h 18m', 'Action'),
 ('Customs Frontline', 5.5, 514, '1h 55m', 'Action'),
 ('Non Negotiable', 5.4, 1200, '1h 27m', 'Action'),
 ('Eye for an Eye 2', 6.6, 530, '1h 30m', 'Action'),
 ('Spiders on a Plane', 5.0, 377, '1h 18m', 'Action'),
 ('Paradise', 6.9, 79, '1h 23m', 'Action'),
 ('Witch Hunter', 5.0, 25, '1h 20m', 'Action'),
 ('Lie Zhan', 6.7, 75, '1h 33m', 'Action'),
 ('12 Gaun', 6.2, 912, '2h 27m', 'Action'),
 ('Conquer: Lahad Datu', 6.6, 534, '2h', 'Action'),
 ('Viswam', 4.2, 649, '2h 35m', 'Action'),
 ('Bastar: The Naxal Story', 6.4, 3300, '2h 4m', 'Action'),
 ('I Am What I Am 2', 7.5, 209, '2h 14m', 'Action'),
 ('Alangu', 8.1, 1200, '2h 11m', 'Action'),
 ('The Moon Thieves', 6.0, 267, '1h 48m', 'Action'),
 ('The Experts', 6.1, 293, '2h 1m', 'Action'),
 ('Siren', 6.4, 2900, '2h 34m', 'Action'),
 ('Lisabi: The Uprising', 5.9, 132, '1h 47m', 'Action'),
 ('Desperado', 6.0, 148, '1h 40m', 'Action'),
 ('The Kingdom', 6.8, 122, '2h 13m', 'Action'),
 ('Taken from Rio Bravo', 3.0, 318, '1h 20m', 'Action'),
 ('Art of Eight Limbs', 3.9, 321, '1h 41m', 'Action'),
 ('Naam', 6.3, 283, '2h 16m', 'Action'),
 ('Kung Fu Games', 3.3, 388, '1h 38m', 'Action'),
 ('Sikaar', 8.3, 683, '2h 30m', 'Action'),
 ('The Plot', 4.8, 391, '1h 40m', 'Action'),
 ('Por', 5.1, 624, '2h 34m', 'Action'),
 ('Devaki Nandana Vasudeva', 6.5, 2700, '2h 8m', 'Action'),
 ('Shu Si Yi Bo', 6.7, 37, '1h 31m', 'Action'),
 ('Big Rage', 3.5, 170, '1h 55m', 'Action'),
 ('Midas', 4.6, 343, '1h 25m', 'Action'),
 ('My Redneck Neighbor: Chapter 2 - Let the Games Begin',
  6.6,
  9,
  '55m',
  'Action'),
 ('Warning 2', 7.1, 893, '2h 5m', 'Action'),
 ('Bangkok Breaking: Heaven and Hell', 5.8, 690, '2h 26m', 'Action'),
 ('Game On', 5.2, 2300, '2h 20m', 'Action'),
 ('Return to the Ring', 5.4, 731, '1h 46m', 'Action'),
 ('Crosspoint', 6.8, 54, '1h 40m', 'Action'),
 ('Gandhi 3', 5.7, 242, '2h 23m', 'Action'),
 ('Anchakkallakokkan', 6.6, 1000, '2h 6m', 'Action'),
 ('Andromeda: 1883', 4.0, 19, '1h 15m', 'Action'),
 ('Love You to Debt', 6.2, 765, '2h 15m', 'Action'),
 ('Lal Salaam', 4.4, 1300, '2h 30m', 'Action'),
 ('Sous écrous', 5.5, 92, '1h 51m', 'Action'),
 ('The Deal', 8.6, 28, '2h 10m', 'Action'),
 ('Sector 17', 5.6, 1300, '2h 26m', 'Action'),
 ('The Firefighters', 5.6, 223, '1h 46m', 'Action'),
 ('Rode College', 6.6, 431, '2h 48m', 'Action'),

In [21]:
q2 = """

create table IMDB_Movies_list(
Title varchar(255),
Rating FLOAT,
Voting INT,
Duration VARCHAR(20),
Genre VARCHAR(20)
);
"""

curr.execute(q2)


insert = """
insert into IMDB_Movies_list
values
(%s, %s, %s, %s, %s)
"""

curr.executemany(insert, list(map(tuple, df.values)))
db_con.commit()